### ISSUE TITLE
Wrong link in install.sh?

### ISSUE THREAD

**Issue by kymlalu** [thetic/klipper-sgp40#6]
I'm not sure but in "install.sh" there's part where it links needed python files to klipper. 
And since i'm having error message with non-existent file, i looked into files and there is  this 

```
# Link extension to Klipper
link_extension() {
    echo -n "Linking extension to Klipper... "
    ln -sf "${SRCDIR}/sgp40.py" "${KLIPPER_PATH}/klippy/extras/sgp40.py"
    ln -sf "${SRCDIR}/voc_algorithm.py" "${KLIPPER_PATH}/klippy/extras/voc_alog.py"
    echo "[OK]"
}
```

Shouldn't be that "voc_algorithm.py be same in link target?

**Comment by thetic** [comment]
thank you
